# Generated by Django 2.2 on 2019-04-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='expiration_notify',
            field=models.BooleanField(default=False),
        ),
    ]
