# Generated by Django 2.1.7 on 2019-03-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='local_name',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='remote_name',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social_network',
            name='token',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
