# Generated by Django 2.1.7 on 2019-03-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190321_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('F', 'FILE'), ('I', 'IMAGE'), ('V', 'VIDEO')], max_length=1),
        ),
    ]
