# Generated by Django 2.0.3 on 2019-04-05 00:02

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_capsule_expiration_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='birthdate',
            field=models.DateField(validators=[main.models.birthdate_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(validators=[main.models.birthdate_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_notification',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
