# Generated by Django 2.0 on 2019-03-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190322_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='dead_man_initial_counter',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capsule',
            name='time_unit',
            field=models.IntegerField(choices=[(0, 'minutes'), (1, 'days'), (2, 'months'), (3, 'years')], null=True),
        ),
    ]
