# Generated by Django 2.2 on 2019-04-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190405_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='facebook_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capsule',
            name='twitter_notify',
            field=models.BooleanField(default=False),
        ),
    ]
