# Generated by Django 2.0 on 2019-03-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190326_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='release_notify',
            field=models.BooleanField(default=False),
        ),
    ]
