# Generated by Django 2.1.7 on 2019-04-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190405_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsule',
            name='facebook_notify',
        ),
        migrations.RemoveField(
            model_name='capsule',
            name='twitter_notify',
        ),
        migrations.AddField(
            model_name='module',
            name='facebook_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='twitter_notify',
            field=models.BooleanField(default=False),
        ),
    ]
