# Generated by Django 2.2 on 2019-04-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_module_release_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsule',
            name='credit_card',
        ),
        migrations.AddField(
            model_name='capsule',
            name='payment_id',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='social_network',
            name='secret',
            field=models.CharField(default='123', max_length=100),
        ),
        migrations.AlterField(
            model_name='social_network',
            name='token',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Credit_card',
        ),
    ]
