# Generated by Django 2.1.7 on 2019-04-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190406_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='emails',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
