# Generated by Django 2.2 on 2019-04-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190403_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_network',
            name='secret',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
